[package]
name = "real-time"
description = "Safely share data with a real-time thread."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = "0.7.1"
